name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry install --extras "test"
        # Ensure CPU-only PyTorch is used
        # poetry run pip install torch==2.1.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
    - name: Run tests
      run: |
        poetry run pytest
